### ISSUE TITLE
Why is there no space after the function name after using the eslint fix all？

### ISSUE THREAD

**Issue by baixiaoyu2997** [npetruzzelli/eslint-config-prettier-standard#10]
standard rule is `Add a space before a function declaration's parentheses.`
but when i use eslint fix all，the space removed
example：
```diff
- function checkNodeVersion (wanted, cliName) {}
+ function checkNodeVersion(wanted, cliName) {}
```
i test on new project  

step1 :
```
npm install --save-dev eslint
npm install --save-dev eslint-config-prettier eslint-config-prettier-standard eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-prettier eslint-plugin-promise eslint-plugin-standard prettier-config-standard
npm install --save-dev --save-exact prettier
npm install --save-dev eslint-config-prettier-standard
```
setp 2:
```json
// .eslintrc
{
  "extends": ["prettier-standard"]
}
```

sorry for my english， can you tell me what I'm missing

**Comment by baixiaoyu2997** [comment]
ok,i find another way  to format code with Standard。
just use vscode  extensions  `Prettier-Standard - JavaScript formatter`+`eslint --init`。

**Comment by eyalch** [comment]
@npetruzzelli I'm also having this issue where ESLint complains about a function having a space after it's name:
> Delete `·` (prettier/prettier)

**Comment by npetruzzelli** [comment]
The ESLint rule that governs the Standard Style rule is: <https://eslint.org/docs/rules/space-before-function-paren>

And it must be disabled. 

Using `eslint-config-prettier-standard` (or any config that properly extends `eslint-config-prettier`) will automatically disable this rule as seen here: 

https://github.com/prettier/eslint-config-prettier/blob/07380e2235cea405822b7c0de20bbecbf2dc6da0/index.js#L77-L78

If you are not using this config in such a way that it disables this rule, or you have the rule set in your config that re-enable rules that conflict with `eslint-plugin-prettier`. Keep in mind that the configs that disable conflicting rules must be the last in your `extends` array, other wise there is a chance that something else after it could re-enable it as easily as you could.

---

> @npetruzzelli I'm also having this issue where ESLint complains about a function having a space after it's name:

For future reference, simply saying "I have a problem" won't help you or others who are trying to help you. You need to provide information about your code or configuration and what steps you've already taken to try to resolve it. Neither I, nor any other repository maintainer, have anyway of knowing whether our repo is even the source of your problem if you don't provide information we can work with.

---

If you continue to have problems, post your eslint config settings as well as the the versions of related dependencies / devDependencies in your `package.json` file.

**Comment by npetruzzelli** [comment]
Please keep in mind that Prettier is an opinionated formatter with deliberately minimal options.

If you want to set rules that conflict with Prettier, such as some of those in JavaScript Standard Style, then the config in this repo is not the correct tool for the job. You would be better served with a process that first executes Prettier and then forwards the results to ESLint or Standard. That kind of workflow is not the goal of this config. 

Tools to accomplish this already exist.

[prettier-standard](https://github.com/sheerun/prettier-standard) is one such tool.

If you want to support plugins beyond what Standard provides, then you should look into [prettier-eslint](https://github.com/prettier/prettier-eslint)

---

The reason I made the config in this repository is because:

1.  I am ok with taking Prettier's opinion over Standard Style's opinion
2.  Files get processed in one pass
3.  It is easier to find plugins for large variety of code editors and IDEs that work with ESLint alone than with other workflows like `prettier-standard` or `prettier-eslint`.

The end result is something that is consistent when the formatting is done by a code editor or a Node process and team members that are not experienced with build systems are less likely to run into problems or conflicts.
