### ISSUE TITLE
Possible to collect all dependencies in one pkg?

### ISSUE THREAD

**Issue by corysimmons** [npetruzzelli/eslint-config-prettier-standard#2]
Kinda a pita to have to install them all in a particular order like that. Any ideas how we could make it so they auto-installed?

Perhaps enabled via flag to keep this pkg modular?

**Comment by npetruzzelli** [comment]
Hi @corysimmons ,

I apologize for taking so long to reply, this must have slipped through the cracks!

The order you install the modules in doesn't matter. I think I was just trying to make it a little easier to digest vs having one giant line to copy and paste, though it has room for improvement.

The package is already modular. It handles its own concerns without reinventing someone else's wheel. You'll see that the packages I depend on also use "peer dependencies" instead of "dependencies".

I do have an idea on how to install them all at once, though I don't see it happening in this repository. If I did, I would be strong arming the peer dependencies of the other module into production or development dependencies, which behave a bit differently as far as npm is concerned.

A wrapper "module" could be made to do the strong arming. It would take the form of a new repository, let's call it `corys-eslint-config-prettier-standard`. We are intentionally breaking the shareable config naming convention, since the repository itself would not be a shareable config.

It would list all peer dependencies as production dependencies in its `package.json` file:

```json
{
  "name": "corys-eslint-config-prettier-standard",
  "version": "1.0.0",
  "dependencies": {
    "eslint": "^4.1.1",
    "eslint-config-prettier": "^2.3.0",
    "eslint-config-prettier-standard": "^1.0.1",
    "eslint-config-standard": "^10.2.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.0",
    "eslint-plugin-prettier": "^2.1.2",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "prettier": "^1.5.2"
  }
}
```

... and have a readme file explaining what the repo is, how to use it, and probably a link back to this repo. Publish that repo to npm and you can install it like any other module.

You would then install this as your project's devDependency. Its use would be identical. There is the potential to have multiple versions of the same module using this approach. You'd be hiding the dependencies from your own package file.

I don't like the suggestion I just gave you, but it would install everything by installing a single module.

Another option would be to provide a single line somewhere in the readme doc that you could copy and paste. It would look like this:

```
npm install --save-dev eslint-config-prettier-standard eslint eslint-config-prettier eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise eslint-plugin-standard eslint-plugin-prettier prettier
```

That would install all the modules with a single command.

**Comment by corysimmons** [comment]
Thanks for the tutorial. =)

**Comment by npetruzzelli** [comment]
@corysimmons - I've added the one liner to the README, hopefully this makes future projects a little easier!

<https://github.com/npetruzzelli/eslint-config-prettier-standard/releases/tag/v2.0.0>
