### ISSUE TITLE
Update `eslint-config-standard` dependency

### ISSUE THREAD

**Issue by nikolay-borzov** [npetruzzelli/eslint-config-prettier-standard#4]
Also, check out [Greenkeeper](https://greenkeeper.io/), it notifies you if one or more dependencies are updated

**Comment by npetruzzelli** [comment]
Hi @nikolay-borzov ,

Thank you for opening the issue. As short as it is, it breaks down into multiple items which I will attempt to tackle one by one. Before that, I would like to apologize for the time it has taken to respond.

**1) Updating dependencies.**

Per PR #3 , I already had plans to update my dependencies. I am starting on that today, which is how I noticed your open issue.

-   `eslint-config-standard` will be updated from **^10.2.1** to **^11.0.0**
-   `eslint-config-prettier` will be updated from **^2.3.0** to **^2.9.0**
-   `eslint-plugin-prettier` will be updated from **^2.1.2** to **^2.6.0**

Since `eslint-config-standard` incremented its major version, I will consider that a breaking change for this repo, and will increment my major version to reflect that.

**2) Checkout Greenkeeper**

Thanks for the heads up. I'm always interested in hearing about new tools. I don't know if I will have the time to check it out in the near future, but I will keep it in the back of my mind for when I do.

**Comment by nikolay-borzov** [comment]
Thanks for the update!
